# Generated by Django 4.2.3 on 2023-09-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, choices=[('yasamal', 'Yasamal'), ('nizami', 'Nizami')], max_length=100, null=True),
        ),
    ]
